### ISSUE TITLE
Use additional categories

### ISSUE THREAD

**Issue by danirabbit** [PlugaruT/pwned-checker#10]
https://github.com/PlugaruT/pwned-checker/blob/9e9cd9cc0709178164485d1376faf654cb0c21ff/data/com.github.plugarut.pwned-checker.desktop.in#L5

There are more categories available that might help users find your app. For example, you could add "Security". Check [the spec](https://standards.freedesktop.org/menu-spec/latest/apas02.html) for any other categories that may apply :)

**Comment by PlugaruT** [comment]
Gonna update the categories in the next release. Thanks.
