### ISSUE TITLE
Send hashed password to service

### ISSUE THREAD

**Issue by tintou** [PlugaruT/pwned-checker#11]
The application is currently sending password to the service, the REST API allows to get SHA-1 hashed password. Please use this solution instead for security reasons.

**Comment by PlugaruT** [comment]
@tintou yes, I know. It's in my pipeline. The next release will have this implemented.

**Comment by PlugaruT** [comment]
The only downside that I see is that it won't be possible to get the number of times a password is present in the database.

**Comment by PlugaruT** [comment]
Closing this because it is implemented in 0.1.8
