### ISSUE TITLE
Checking the same e-mail twice succesively gives different results

### ISSUE THREAD

**Issue by arubislander** [PlugaruT/pwned-checker#12]
**Summary:**
When I enter an email address I know has been leaked, when checking it for the first time the app corrected reports it compromised. But pressing [Check!] again gives the result that everything is OK.

**How to reproduce:**
Enter email you know to have been in a security breach in the lower text box.
Click on [Check!]
Click on [Check!] again

**Expected result:**
The app should report that the account was involved in one or more breaches both times

**Actual result:**
The app reports that the account was involved in one or more breaches the first time.
The app Congratulates the user on their carefulness on the second time.

**Comment by PlugaruT** [comment]
Thanks for the report. I will look into it.

**Comment by PlugaruT** [comment]
The strange part is that I can't replicate this bug. I have tested no the application and it behaves as expected.

**Comment by arubislander** [comment]
I guess between the logging of the issue and now the bug has been resolved, because I cannot replicate it now either. I will consider this solved and close the issue. Thanks!
