### ISSUE TITLE
Delete the end period in app description

### ISSUE THREAD

**Issue by NathanBnm** [PlugaruT/pwned-checker#20]
As recommended by elementary documentation you should not add a period to the end of the small description sentence. Other apps don't have it:

![image](https://user-images.githubusercontent.com/45366162/53699355-c8603a00-3de7-11e9-9879-a53766c51587.png)

This is in `appdata.xml` at line `8` (you may have to update po files then)

**Comment by PlugaruT** [comment]
Thanks. I'll remove it.
