### ISSUE TITLE
AppCenter Review: Please use elementary OS defaults in screenshots

### ISSUE THREAD

**Issue by danirabbit** [PlugaruT/pwned-checker#8]
Hey thanks for submitting your app to AppCenter! I've marked your latest release as "Needs Fixing" since the supplied screenshots don't seem to use elementary OS default settings (particularly the window controls). Please update your screenshots to use default settings and publish a new release :)

**Comment by PlugaruT** [comment]
Hi,
Thanks.
Done :)
