### ISSUE TITLE
AppCenter Review: Update OARS data

### ISSUE THREAD

**Issue by danirabbit** [PlugaruT/pwned-checker#9]
https://github.com/PlugaruT/pwned-checker/blob/3f0bd981b0bd2ef83c63221a6e962ea99cff75e9/data/com.github.plugarut.pwned-checker.appdata.xml.in#L92

After some discussion with the review team, we feel it would be more accurate for this line to read "intense" since a username and password would be considered as "user-identifiable diagnostics"

**Comment by PlugaruT** [comment]
Hi,
fixed in the latest release.
Thanks
